### ISSUE TITLE
Replace purescript-react-basic-hooks with just purescript-react-basic

### ISSUE THREAD

**Issue by paluh** [milesfrain/purescript-faq#1]
It seems that [_purescript-react-basic_](https://github.com/lumihq/purescript-react-basic) is the core library right now and it links to both _hooks_ and _classic_ libs as the possible API for components.
Would you like to change the link in the frameworks section? Please, just let me know - I would happily provide a PR with this cosmetic change.

**Comment by milesfrain** [comment]
Yes. Please make a PR!
