### ISSUE TITLE
(Probably) outdated explanation for explicit instance naming requirement

### ISSUE THREAD

**Issue by triallax** [milesfrain/purescript-faq#11]
[The "Why must I manually name my instances?" section](https://github.com/milesfrain/purescript-faq#why-must-i-manually-name-my-instances) states:
> Sometimes it's not straightforward to infer names, and custom names can make FFI more convenient.

My issue is not with the first point, but with the second one. I think it's currently generally discouraged to use PureScript instances from JS (e.g. see https://github.com/purescript/purescript/issues/3182).

**Comment by milesfrain** [comment]
That makes sense. Removed the second point.

**Comment by triallax** [comment]
You could also mention that they aid in readability of generated code when e.g. debugging.
