### ISSUE TITLE
"Why must I manually name my instances?" section should be removed

### ISSUE THREAD

**Issue by triallax** [milesfrain/purescript-faq#12]
See https://github.com/purescript/purescript/pull/4085.

I might make a PR for this, but we should wait till the feature is released before we merge it.

**Comment by milesfrain** [comment]
Good point. Just edited that section to note that this will be available in the next release. Feel free to make a PR to remove that section once `0.15` is published.

**Comment by JordanMartinez** [comment]
Just to be clear, the PR above made instance names optional. The decision to drop instance names entirely hasn't yet been made, so I'm not sure such a breaking change would be made by `v0.15`. If an instance name can still be defined, one can still use it via FFI (though this is currently strongly discouraged). I don't know the full context around why one would do that, so I can't comment any further.

**Comment by triallax** [comment]
Thanks for the clarification (I was aware of all that, but it should clear up any mistaken beliefs others might have had).

The edited section does not imply the removal of instance names; it just says that "automatic instance naming will be available in the next compiler release (0.15)," which I think is very clear.

**Comment by JordanMartinez** [comment]
But to clarify, this feature should first appear in `v0.14.2`, not `v0.15.0`, as this isn't a breaking change. One can "opt-in" to the feature by not specifying a name. However, those that still use a name will still continue to work.

**Comment by triallax** [comment]
Oh, yeah, that does make sense. @milesfrain maybe just remove the `0.15` part, and just say "next compiler release"?

**Comment by milesfrain** [comment]
> just say "next compiler release"

Edited with `0.14.2` to make it more obvious to future readers when that section can be deleted.
