### ISSUE TITLE
`.` actually can be used on more on functions in Haskell

### ISSUE THREAD

**Issue by triallax** [milesfrain/purescript-faq#8]
> Note that `<<<` in PureScript and Haskell allow for composing more than just functions, while `<<` in Elm and **`.` in Haskell only work for functions.**

Emphasis mine. This is actually incorrect. See [here](https://hackage.haskell.org/package/base-4.14.0.0/docs/Control-Category.html#v:.).

**Comment by milesfrain** [comment]
I don't have enough Haskell expertise to correct this one. (I believe I just lifted the haskell point from a slack discussion). Feel free to propose a more accurate comparison.

**Comment by triallax** [comment]
I actually don't know a lot about Haskell either (aside from what I learned from PureScript, of course), but I'll try my best.
